<?php

$wopeAutoload['Wope_Log'] = dirname(__FILE__).'/Wope_Log.class.inc';
$wopeAutoload['Wope_Log_Writer_Stream'] = dirname(__FILE__).'/writer/Wope_Log_Writer_Stream.class.inc';
$wopeAutoload['Wope_Log_Filter_Priority'] = dirname(__FILE__).'/filter/Wope_Log_Filter_Priority.class.inc';
$wopeAutoload['Wope_Log_Formatter_Html'] = dirname(__FILE__).'/formatter/Wope_Log_Formatter_Html.class.inc';
$wopeAutoload['Wope_Log_Formatter_Simple'] = dirname(__FILE__).'/formatter/Wope_Log_Formatter_Simple.class.inc';
?>