<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


/* $config_module_identification['menu']['Mon compte'] = 'user/index.php?part=account'; */
$config_module_identification['menu']['Mes fichiers'] = 'file_browser/';
$config_module_identification['menu']['Mes informations'] = 'user/index.php?part=info';
$config_module_identification['menu']['Mes préférences'] = 'user/index.php?part=pref';
$config_module_identification['menu']['Mes catégories'] ='user/index.php?part=category';
$config_module_identification['menu']['Mes visiteurs'] ='user/index.php?part=home#visit';
//$config_module_identification['menu']['Déconnexion'] = 'index.php?logout';

?>
