<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/

//******************************************************************************
//Annales

$that=array();
//labels provenant action.php
$that['file_too_big']='Fichier trop gros';
$that['file_size_too_big']='Taille de fichier trop grosse';
$that['file_partially']='Fichier partiellement';
$that['no_file_send']='Aucun fichier envoyé';

//labels provenant index.php
$that['relative_folder']='Dossier parent';
$that['go_root']='Aller à la racine';
$that['no_type_known']='Pas de type connu';
$that['add_files']='Ajouter un fichier';

$label['annales'] = $that;

?>
