<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//Annonces

$that=array();
$that['page']='Page';
$that['annonce_actif']='Annonce activée';
$that['annonce_noactif']='Annonce non activée';
$that['mesannonces']='Mes annonces';

// labels provenanr de modif.php
$that['modif']='Annonce modifiée. Elle sera publiée une fois le contrôle de l\'administrateur effectué';

//labels provenant de admin.php
$that['admin_annonce']='Administration des annonces';
$that['supr_image']='Supprimer l\'image';
$that['supprimer']='Supprimer';

//labels provenant de alertes.php
$that['alarm_manage']='Gestion de mes alertes';
$that['tick_categ']='Cochez les catégories pour lesquelles vous souhaitez être prévenu(e) à  chaque nouvelle proposition : ';
$that['categ']='Catégories';

//labels provenant de edit_cat.php
$that['edit_categ_2']='Edition des catégories';
$that['no_name_categ']='Vous n\'avez pas saisi de nom pour la catégorie';
$that['modify_categ']='Modifier une catégorie';
$that['add_categ']='Ajouter une catégorie';
$that['categ_parent']='Catégorie parente : ';
$that['no_one']='Aucune';

//labels provenant de index.php
$that['small_announce']='Peties annonces';
$that['new_annonce']='Nouvelle annonce';
$that['my_annonce']='Mes annonces';
$that['my_alerte']='Mes alertes';
$that['edit_categ']='Editer les catégories';
$that['all']='Toutes';
$that['ask']='Demandes';
$that['proposition']='Propositions';
$that['lost']='Perdu';
$that['finded']='Trouvé';
$that['edit_announce']='Editer mon annonce';
$that['del_announce']='Supprimer mon annonce';
$that['no_announce']='Aucune annonce';
$that['admin']='Administrer';
$that['activer']='Activer';
$that['desactiver']='Désactiver';
$that['poste']='Postée le';

//labels provenant de new.php
$that['alarm_manage']='Gestion de mes alertes';
$that['no_type']='Vous n\'avez pas choisi de type pour l\'annonce';
$that['no_categ']='Vous n\'avez pas choisi de catégorie pour l\'annonce';
$that['no_element']='Vous devez cocher au moins un élèment concerné par l\'annonce';
$that['no_title']='Vous n\'avez pas choisi de titre pour l\'annonce"';
$that['no_detail']='Vous n\'avez pas rempli le détail de l\'annonce';
$that['no_contact']='Vous n\'avez pas rempli le champ contact';
$that['no_duration']='Vous n\'avez pas choisi de durée pour l\'annonce"';
$that['no_figure_duration']='Vous devez saisir des chiffres pour la durée de l\'annonce"';
$that['duration_max']='La durée maximale d\'une annonce est de 30 jours"';
$that['propose']='Propose';
$that['seek']='Cherche';
$that['photo']='Photo (jpg)';
$that['announce_duration']='Durée de l\'annonce (jours) ';
$that['duration_max_2']='(<strong>maximum 30 jours</strong> mais vous pourrez la relancer après)';
$that['miss_categ']='Si vous pensez qu\'il manque une catégorie, contactez le webmaster pour la rajouter';
$that['miss_element']='Si vous pensez qu\'il manque des élèments, contactez le webmaster pour en rajouter';
$that['type']='Type';
$that['categorie']='Catégories';
$that['element']='Elements concernés';
$that['contact']='Contact';
$that['ok']='Annonce soumise. Elle sera publiée une fois le contrôle de l\'administrateur effectué';
$that['pasjpg']='L\'image n\'est pas en JPG';


$label['annonces'] = $that;
?>
