<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/



//******************************************************************************
//Clubs_assos

//labels provenant de index.php
$that=array();
$that['title']='Intitulé';
$that['description']='Description';
$that['web_page']='Page Web';
$that['mail_asso']='Email de l\'asso';
$that['loggin_asso']='Login de l\'asso';
$that['name_person_in_charge']='Nom du responsable';
$that['tel_person_in_charge']='Tel du responsable';
$that['person_in_charge']='Responsable';

$label['clubs_assos'] = $that;


?>
