<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//COVOITURAGE

$that=array();


$that['post_detail_way']='Annonces de covoiturage';
$that['add_new_way']='Nouveau covoiturage';

//labels provenant de detail.php
$that['covoiturage']='Covoiturage';
$that['currently_consultable']='à consulter';
$that['offer']='Offre(s)';
$that['request']='Demande(s)';
$that['divide_car']='J\'ai un véhicule à partager';
$that['seek_car']='Je cherche un véhicule';
$that['departure_date']='La date du départ';
$that['departure_place']='Lieu de Départ';
$that['departure_zipcode']='N° du Département de Départ';
$that['arrival_place']='Lieu d\'arrivée';
$that['arrival_zipcode']='N° du Département d\'Arrivée';
$that['note']='Notes éventuelles';
$that['dpt_crossed']='Départements traversés';
$that['way']='Trajet';
$that['proposed_by']='Proposé par';
$that['proposal_out_date']='Cette proposition n\'existe plus';

//labels provenant de index.php
$that['seek']='Recherche';
$that['new_proposal']='Nouvelle proposition';

//Labels povenant de new.php
$that['save_way']='Le trajet a bien été enregistré.';
$that['my_situation']='Ma situation';
$that['tick_dpt_crossed']='Sélectionnez les départements traversés au cours du trajet';
$that['save_proposal']='Enregistrer la proposition';

//Labels provenant de recherche.php
$that['proposal_list']='Liste des propositions';
$that['ignore']='ignore';
$that['tick_dpt_seeked']='Saisissez le département recherché :';
$that['dpt']='Département';
$that['specify_zipcode']='Précisez un code de département<br/>(Ex : 10) dans votre recherche';

//labels provenant de covoiturage.class.inc
$that['no_way_proposed']='Aucune offre de covoiturage ne convient.';
$that['no_way_searched']='Aucune recherche de covoiturage n\'est compatible.';

$label['covoiturage'] = $that;

?>
