<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//CREDITS

//labels provenant de index.php
$that=array();

$that['ask_webmaster']='Pour toute demande relative à la configuration du site...<a href="mailto:[1]">contactez le webmaster.</a>';
$that['ask_conceptor']='Vous désirez de plus amples renseignements sur le portail <b>MeetMind</b>, <a href="mailto:contact@wope-project.org">contactez ses concepteurs.</a><br/>Nous nous ferons un plaisir d\'étudier vos attentes.';
$that['demo_site']='Site de démonstration du portail MeetMind';
$that['this_site_conceptor']='Le site <b>[1]</b> a été réalisé par <a href="http://www.wope-project.org">Wope</a>.';
$label['credit'] = $that;

?>
