<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//Emplois du temps

//labels provenant de affiche.php
$that=array();
$that['good_and_bad_browser']='L\'affichage est optimum sous tout les navigateurs qui respectent les standards Web comme par exemple <a href="http://www.mozilla-europe.org/fr/products/firefox/">Firefox</a>.<br />Internet Explorer ne respectant pas les standards, il ne pourra donc afficher cette page correctement.';
$that['made_by_dme']='Cet emploi du temps est le reflet de celui fourni par la DME et des informations personnelles que vous désirez y ajouter.';
$that['non_readable']='Emploi du temps non disponible !';
$that['change']='Modifier mon emploi du temps';

$label['emploi'] = $that;

?>
