<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//events

$that=array(); 
//labels provenant admin.php
$that['edit_event']='Edition des événements';
$that['edit_type_event']='Edition des types d\'événements';

//label provenant de edit_type.php
$that['image_mini']='Image (mini)';
$that['add_type']='Ajouter un type';

//label provenant de index.php
$that['no_event']='Aucun événement';
$that['add_event']='Ajouter un événement';
$that['post_event']='Afficher tous les événements';
$that['next_events']='Evénements à venir';
$that['event_recorded']='Evénement soumis, il sera publié après validation par un modérateur.';
$that['event_recorded_webmaster']='Evénement soumis.';
$that['events_this_day']='Evénements le : ';
$that['header_title']='Agenda';

//label provenant de new.php
$that['root']='Evénement soumis. Il sera publié après validation par un modérateur.';
$that['image_jpg']='Image (jpg)';
$that['type_event']='Type d\'événement';
$that['no_type_event']='Si vous ne trouvez pas votre type d\'événement , contactez le webmaster pour le rajouter';
$that['news_recorded']='Actualité soumise, elle sera publiée après validation par un modérateur.';
$that['news_recorded_webmaster']='Actualité soumise.';


$that['event_list']='Liste des évenements';

$label['events'] = $that;


?>
