<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//faq

$that=array();
//labels provenant admin.php
$that['edit_question']='Edition des questions';
$that['edit_type_event']='Edition des types d\'Evènements';

//labels provenant detail.php
$that['faq']='Foire aux questions';
$that['no_question']='Aucune question !';

//labels provenant edit_type.php
$that['edit_type_faq']='Edition des types de FAQ';

//labels provenant edit_type.php
$that['edit_type']='Editer les types';
$that['faq_content']='La foire aux questions (FAQ) regroupe un ensemble de questions qui nous sont posées fréquemment. Merci de consulter cette faq avant de nous contacter.<br/>
  Néanmoins, si votre question ne trouve pas sa réponse ici, n\'hésitez pas à poser votre question sur le forum ou par mail à ';
$that['no_categ']='Aucune catégorie';

$label['faq'] = $that;

?>
