<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//General

$that['administration']='Administration';
$that['admin']='Administration';
$that['avatar']='Avatar';
$that['author']='Auteur';
$that['edit']='Editer';
$that['entry']='Entrée';
$that['cancel']='Annuler';
$that['delete']='Effacer';
$that['add']='Ajouter';
$that['name']='Nom';
$that['first_name']='Prénom';
$that['nickname']='Surnom';
$that['modify']='Modifier';
$that['save']='Enregistrer';
$that['saving']='Enregistrement';
$that['del_change']='Annuler les modifications';
$that['add_success']='Ajout réussi';
$that['update_success']='Mise à jour réussie';
$that['supress_success']='Supression réussi';
$that['title']='Titre ';
$that['status']='Etat';
$that['detail']='Détail ';
$that['contact']='Contact ';
$that['trombi_card']='Fiche trombi ';
$that['activate']='Activer ';
$that['info']='Informations ';
$that['seek']='Chercher';
$that['page']='Page';
$that['Page']='Page';
$that['type']='Type';
$that['uvs']='UVs';
$that['info_2']='Infos';
$that['opinion']='Avis';
$that['alls']='Tous';
$that['phone']='Téléphone';
$that['date']='Date';
$that['open']='Ouvrir';
$that['move_to']='Déplacer vers';
$that['seen']='Aperçu';
$that['information'] = 'Information'; 
$that['source'] = 'Source';
$that['no_one']='Aucun';
$that['no_one_2']='Aucune';
$that['move']='Déplacer';
$that['options']='Options';
$that['login']='Login';
$that['Loading ...']='Chargement ...';
$that['password']='Password';
$that['bold']='Gras';
$that['italic']='Italique';
$that['underligned']='Souligné';
$that['quote']='Citer';
$that['smileys']='Smileys';
$that['bond']='Lien';
$that['id']='ID';
$that['comment']='Commentaire';
$that['msg']='Message';
$that['mail']='E-mail';
$that['ok']='Ok';
$that['edit']='Editer';
$that['close']='Fermer';
$that['minimize']='Réduire';
$that['no']='Non';
$that['yes']='Oui';
$that['description']='Descriptif';
$that['hide']='Cacher';
$that['normal']='Normal';
$that['in_top']='En Haut';
$that['page_top']='Haut de la page';
$that['go_to_top']='Aller en haut';
$that['go_to_bottom']='Aller en bas';
$that['top']='Monter';
$that['bottom']='Descendre';
$that['subject']='Sujet';
$that['link']='Lien';
$that['tree_structure']='Arborescence';
$that['back']='Retour';
$that['and']='ET';
$that['or']='OU';
$that['re']='RE'; //RE : for forum subjet reply
$that['forum']='Forum';
$that['personal_details']='Coordonnées';
$that['credit']='Crédits';
$that['summary']='Sommaire';
$that['survey']='sondage';
$that['event']='Evénements';
$that['small_announces']='Petites annonces';
$that['graphics']='Graphismes';
$that['codriving']='Covoiturage';
$that['weather']='Météo';
$that['television']='Télé';
$that['google']='Google';
$that['advert']='Pub';
$that['msg_integration']='Intégration messagerie';
$that['pulsation']='Pulsation';
$that['trombi']='Trombinoscope';
$that['profile']='Fiche';
$that['club_assos']='Clubs et assos';
$that['integration']='Intégration';
$that['project_management']='Gestion de projets';
$that['radio']='Radios';
$that['directory']='Annuaire';
$that['translation']='Traduction';
$that['postit']='Pense-bête';
$that['info_uv']='Infos uv';
$that['title1']='Titre1';
$that['title2']='Titre2';
$that['external_link']='Lien externe';
$that['internal_link']='Lien interne';
$that['right']='droite';
$that['home']='Accueil';
$that['task']='Tâche';
$that['file']='Fichier';
$that['notif']='Notification';
$that['folder']='Dossier';
$that['root']='Racine';
$that['new_folder']='Nouveau Dossier';
$that['create_folder']='Creer un dossier';
$that['create']='Créer';
$that['add_folder']='Ajouter un fichier';
$that['send']='Envoyer';
$that['post']='Poster';
$that['question']='Question';
$that['erase']='Effacer';
$that['desactivate']='Désactiver';
$that['answer']='Réponse';
$that['return']='Retour';
$that['action']='Action';
$that['validate']='Valider';
$that['hour']='Heure';
$that['from']='Du';
$that['to']='Au';
$that['ddmmyyyy']='jj/mm/aaaa';
$that['place']='Lieu';
$that['image']='Image';
$that['calendar']='Calendrier';
$that['mail']='Email';
$that['annuler']='Annuler';
$that['annul_modifs']='Annuler les modifications';
$that['enregistrer']='Enregistrer';
$that['major']='Branche';
$that['major_specialisation']='Filière';
$that['visible']='Visible';
$that['new']='Nouveau';
$that['seek']='Recherche';
$that['alert']='Alert';
$that['relog']='Vous semblez être déconnecté. Veuillez vous reconnecter.';
$that['print']='Imprimer';
$that['fail']='Echec';
$that['undo']='Annuler';
$that['undo_success']='Anulation réussie';

$that['package_no_loaded']='Le package <b>[1]</b> est nécessaire ici, contactez <a href="[2]">votre administrateur de portail</a>';
$that['package_no_loaded_feature']='Pour bénéficier de la fonction "[1]" demandez l\'installation du package <b>[2]</b> à <a href="[3]">votre administrateur de portail</a>';
$that['add_right']='Ajouter le droit';

//Day of week

$that['monday']='lundi';
$that['tuesday']='mardi';
$that['wednesday']='mercredi';
$that['thursday']='jeudi';
$that['friday']='vendredi';
$that['saturday']='samedi';
$that['sunday']='dimanche';


$label['kernel'] = $that;
$label['main'] = $that;
$label['general'] = $that;

$that=array();

$that['erreur']='Erreur';
//labels provenant 403.php
$that['error_403']='Erreur 403';
$that['no_authorization']='Vous n\'avez pas l\'autorisation d\'afficher cette page.';
$that['back_index']='Revenir à l\'index';

//labels provenant 404.php
$that['error_404']='Erreur 404';
$that['no_page']='La page que vous demandez n\'existe pas.';

//labels provenant need_auth.php
$that['no_page_right']='La page que vous demandez n\'est pas accessible pour des raisons de droits.';
$that['no_page_need_id']='La page que vous demandez ne peut être affichée. Vous devez vous identifier.';
$that['bad_psw']='Le mot de passe est incorrect.';

$that['count_not_activate']='Si vous n\'avez pas encore activé votre compte,  activez le maintenant';  //Labelprob oliv => sid le pd
$that['no_page_authorization']='Vous ne possedez pas les autorisations necessaires pour afficher cette page.';
$that['why_here']='Vous estes arrive ici pourquoi ?';

//labels en provenance de form_submit_error.php
$that['submit_error_form']='Formulaire de soumission de bug';

$label['erreurs'] = $that;

//labels provenant de gestion_module.php
$that['my_modul']='Mes modules';
$that['add_modul']='Modules';
$that['down_modul']='Déplacer ce module vers le bas';
$that['up_modul']='Déplacer ce module vers le haut';
$that['del_modul']='Supprimer le module';
$that['no_more_modul']='Aucun autre module n\'est disponible.';

$label['modul'] = $that;

//colors
$that['red'] = 'rouge';
$that['darkorange'] = 'orange';
$that['magenta'] = 'magenta';
$that['darkgreen'] = 'vert foncé';
$that['blue'] = 'bleu';
$that['purple'] = 'violet';
$that['brown'] = 'brun';
$that['dodgerblue'] = 'bleu ciel';

$label['colors'] = $that;

$that['wrote'] = 'a écrit';
$that['Quotation'] = 'Citation';

$label['bbcode'] = $that;
?>
