<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//Wheather code 0
$that['tornado'] = 'Tornade';
//Wheather code 1
$that['tropical storm'] = 'Tempête tropicale';
//Wheather code 2
$that['hurricane'] = 'Ouragan';
//Wheather code 3
$that['severe thunderstorms'] = 'Orages violents';
//Wheather code 4
$that['thunderstorms'] = 'Orages';
//Wheather code 5
$that['mixed rain and snow'] = 'Averses et chutes de neige';
$that['rain/snow showers'] = 'Averses et chutes de neige';
$that['rain/snow'] = 'Pluies et neige';
//Wheather code 6
$that['mixed rain and sleet'] = 'Averses et verglas';
//Wheather code 7
$that['mixed snow and sleet'] = 'Chutes de neige et verglas';
//Wheather code 8
$that['freezing drizzle'] = 'Bruine verglaçante';
//Wheather code 9
$that['drizzle'] = 'Bruine';
//Wheather code 10
$that['freezing rain'] = 'Pluies verglaçantes';
//Wheather code 11
$that['showers'] = 'Averses';
$that['light rain/wind'] = 'Faibles pluies et vent';
$that['light rain/windy'] = 'Faibles pluies et vent';
$that['light rain'] = 'Faible pluie';
$that['am showers'] = 'Averses le matin';
$that['am light rain'] = 'Légère pluie matinale';
$that['rain'] = 'Pluie';
//Wheather code 12
$that['showers'] = 'Averses';
$that['rain/wind'] = 'Averses et vent';
//Wheather code 13
$that['snow flurries'] = 'Tempête de neige';
//Wheather code 14
$that['light snow showers'] = 'Petites chutes de neige';
//Wheather code 15
$that['blowing snow'] = 'Chutes de neige avec vent fort';
//Wheather code 16
$that['snow'] = 'Neige';
//Wheather code 17
$that['hail'] = 'Grêle';
//Wheather code 18
$that['sleet'] = 'Verglas';
//Wheather code 19
$that['dust'] = 'Poussière';
//Wheather code 20
$that['foggy'] = 'Brumeux';
$that['fog'] = 'Brumeux';
//Wheather code 21
$that['haze'] = 'Brume';
//Wheather code 22
$that['smoky'] = 'Très Brumeux';
//Wheather code 23
$that['blustery'] = 'Tonerre';
//Wheather code 24
$that['windy'] = 'Venteux';
//Wheather code 25
$that['cold'] = 'Froid';
//Wheather code 26
$that['cloudy'] = 'Nuageux';
//Wheather code 27
$that['mostly cloudy (night)'] = 'Assez nuageux';
$that['mostly cloudy'] = 'Assez nuageux';
//Wheather code 28
$that['mostly cloudy (day)'] = 'Assez nuageux';
//Wheather code 29
$that['partly cloudy (night)'] = 'Peu nuageux';
//Wheather code 30
$that['partly cloudy (day)'] = 'Peu nuageux';
$that['am clouds/pm sun'] = 'Matin nuageux';
//Wheather code 31
$that['clear (night)'] = 'Dégagé';
//Wheather code 32
$that['sunny'] = 'Ensoleillé';
//Wheather code 33
$that['fair (night)'] = 'Doux';
//Wheather code 34
$that['fair (day)'] = 'Doux';
$that['fair'] = 'Doux';
//Wheather code 35
$that['mixed rain and hail'] = 'Averses et grêle';
$that['showers late'] = 'Averses en soirée';
//Wheather code 36
$that['hot'] = 'Chaud';
//Wheather code 37
$that['isolated thunderstorms'] = 'Orages isolés';
//Wheather code 38
$that['scattered thunderstorms'] = 'Orages dispersés';
//Wheather code 39
$that['scattered thunderstorms'] = 'Orages dispersés';
//Wheather code 40
$that['scattered showers'] = 'Averses éparses';
//Wheather code 41
$that['heavy snow'] = 'Fortes chutes de neige';
//Wheather code 42
$that['scattered snow showers'] = 'Fortes chutes éparses de neige';
//Wheather code 43
$that['heavy snow'] = 'Fortes chutes de neige';
//Wheather code 44
$that['partly cloudy'] = 'Peu nuageux';
//Wheather code 45
$that['thundershowers'] = 'Tonerre';
//Wheather code 46
$that['snow showers'] = 'Fortes chutes de neige';
//Wheather code 47
$that['isolated thundershowers'] = 'Coups de tonerre isolés';
//Wheather code 3200
$that['not available'] = 'Meteo indisponible';





/*
$that['Sun']='Soleil';
$that['Sunshine:']='Lever';
$that['Sunset:']='Coucher';
$that['Partly Cloudy']='Partiellement Nuageux';
$that['Sunny']='Ensoleillé';
$that['Cloudy / wind']='Nuageux / Vent';
$that['Mostly cloudy']='Assez nuageux';
$that['Mostly sunny']='Assez ensoleillé';
$that['Rain / wind']='Pluie / vent';
$that['Rain']='Pluie';
$that['Am showers']='Averses matinales';
$that['Mostly cloudy / wind']='Assez nuageux / vent';
$that['Haze']='Brume';
$that['Pm rain / snow showers']='Pluie / neige en aprèm';
$that['Snow shower']='Tombée de neige';
$that['Heavy rain / wind']='Forte pluie / vent';
$that['Heavy rain']='Forte pluie';
$that['Mostly cloudy and windy']='Assez nuageux, vents';
$that['Cloudy']='Nuageux';
$that['Am snow showers']='Chutes de neige matin';
$that['Rain / snow']='Pluie / neige';
$that['Light rain']='Légère pluie';
$that['Pm showers']='Averses l\'après-midi';
$that['Light rain / wind']='Faible pluie / vent';
$that['Partly cloudy / wind']='Part. nuageux / vent';
$that['Few showers / wind']='Faible averses / vent';
$that['Showers / wind']='Averses / vent';
$that['Fair']='Clair';
$that['Showers']='Averses';
$that['T-storms']='Orages';
$that['Few showers']='Quelques Averses';
$that['Foggy']='Brouillard';
$that['Fog']='Brouillard';
$that['Sunny intervals']='Passages ensoleillés';
$that['Scattered showers']='Averses éparses';
$that['Clear']='Dégagé';
$that['Light snow']='Faible neige';
$that['Am snow']='Neige matinale';
$that['Flurries']='Bourrasques';
$that['Few snow showers']='Quelques chutes de neige';
$that['Showers in the vicinity']='Averses à proximité';
$that['Scattered t-storms']='Orages épars';
$that['Isolated t-storms']='Orages isolés';
$that['Light rain shower']='Pluie légère';
$that['Rain / snow showers']='Averses / neige';
$that['Light showers']='Légères averses';
$that['Clear / wind']='Dégagé / vent';
$that['Snow / wind']='Neige / vent';
$that['Snow']='Neige';
$that['Pm snow']='Neige l\'après-midi';
$that['Pm snow showers']='Chutes de neige l\'après-midi';
$that['Rain / snow / wind']='Pluie / neige / vent';
$that['Light rain / freezing rain']='Légére pluie verglaçante';
$that['Wintry mix']='Mélange hivernal';
$that['Sleet']='Neige fondue';
$that['Thundery showers']='Averses orageuses';
$that['Light snow showers']='Légères chutes de neige';
$that['Heavy snow']='Neige abondante';
$that['Heavy showers']='Fortes averses';
$that['Misty']='Brumeux';
$that['Light wintry mix']='Mélange hivernal Léger';
$that['Heavy snow / wind']='Neige abondante / vent';
$that['Am rain / snow']='Pluie / neige matinale';
$that['Partly cloudy and windy']='Parti. nuageux avec vent';
$that['Light drizzle']='Légère bruine';
$that['Am clouds / pm sun']='Nuages mat. / aprèm. ensol.';
$that['Cloudy and windy']='Nuageux avec vents';
$that['Light snow and windy']='Neige légère avec vents';
$that['Light rain shower and windy']='Pluie légère avec vents';
$that['Light rain and windy']='Pluie légère et vents';
$that['Heavy rain shower']='Forte pluie';
$that['Rain / snow showers / wind']='Pluie / neige / vent';
$that['Rain shower']='Averses';
$that['Rain and snow']='Pluie et neige';
$that['Light drizzle and windy']='Légères bruines et vents';
$that['Drifting snow']='Neige dérivante';
$that['Flurries / wind']='Rafales de vent / vent';
$that['Scattered flurries']='Rafales de vent';
$that['Am rain / snow showers']='Pluie le matin / neige';
$that['Heavy snow showers']='Tombée de neige abondante';
$that['Blowing snow and windy']='Neige avec vent';
$that['Fair and windy']='Clair avec vent';
$that['Light snow and sleet']='Faible neige et verglas';
$that['Snow and fog']='Neige et brouillard';
$that['Light freezing drizzle']='Bruines légères glacées';
$that['Drizzle']='Bruine';
$that['Mostly clear']='Assez dégagé';
$that['Pm snow showers / wind']='Neige / vent';
$that['Cloudy']='Couvert';
$that['Mostly Cloudy']='Très nuageux';
$that['Partly Cloudy']='Nuageux';
$that['Light Rain']='Pluie légère';
$that['Showers']='Averses';
$that['Rain']='Pluie';
$that['AM Showers']='Averses matinales';
$that['Fog']='Brouillard';
$that['Few Showers']='Quelques averses';
$that['Mostly Sunny']='Plutôt ensoleillé';
$that['Sunny']='Ensoleillé';
$that['Scattered Flurries']='Fortes rafales';
$that['AM Clouds/PM Sun']='Nuages Matin/Soleil A-Midi';
$that['Isolated T-Storms']='Orages Isolés';
$that['Scattered Thunderstorms']='Orages Violents';
$that['PM Showers']='Averses A-Midi';
$that['PM Showers/Wind']='Averses A-Midi/Vent';
$that['Rain/Snow Showers']='Averses de Pluie/Neige';
$that['Few Snow Showers']='Faibles averses de neige';
$that['Cloudy/Wind']='Nuageux/Vent';
$that['Flurries/Wind']='Bourrasques/Vent';
$that['Mostly Cloudy/Windy']='Plutôt Nuageux/Vent';
$that['Rain/Thunder']='Pluie/Orage';
$that['Partly Cloudy/Windy']='Nuageux/Vent';
$that['AM Rain/Snow Showers']='Pluies/neige Matinales';
$that['Light Rain/Wind']='Pluie Légère/Vent';
$that['Showers/Wind']='Averses/Vent';
$that['Mostly Sunny/Wind']='Plutôt Ensoleillé/Vent';
$that['Flurries']='Bourrasques';
$that['Rain/Wind']='Pluie/Vent';
$that['Sct Flurries/Wind']='fortes rafales/Vent';
$that['Sct Strong Storms']='Orages Violents';
$that['PM T-Storms']='Orages A-Midi';
$that['Thunderstorms']='Orages';
$that['Sunny/Windy']='Ensoleillé/Vent';
$that['AM Thunderstorms']='Orages Matinaux';
$that['AM Rain']='Pluie Matinale';
$that['Iso T-Storms/Wind']='Orages Isolés/Vent';
$that['Rain/Snow']='Pluie/Neige';
$that['Sct T-Storms/Wind']='Orages Violents/Vent';
$that['AM Showers/Wind']='Averses Matinales/Vent';
$that['Sct Snow Showers']='Fortes averses de neige';
$that['Snow to Ice/Wind']='Verglas/Vent';
$that['Snow to Rain']='Neige fondue';
$that['AM Light Rain']='Pluie légère le matin';
$that['PM Light Rain']='Pluie légère';
$that['PM Rain']='Pluie';
$that['Snow Showers']='Averses de Neige';
$that['Rain to Snow']='Pluie puis Neige';
$that['PM Rain/Snow']='Pluie/Neige A-Midi';
$that['Few Showers/Wind']='Quelques Averses/Vent';
$that['Snow/Wind']='Neige/Vent';
$that['PM Rain/Snow Showers']='Averses Neige/pluie A-Midi';
$that['PM Rain/Snow/Wind']='Pluie/neige/vent A-Midi';
$that['Rain/Snow Showers/Wind']='Vent Averses Pluie/Neige';
$that['Rain/Snow/Wind']='Pluie/Neige/Vent';
$that['Light Snow']='Faibles averses/Neige';
$that['PM Snow']='Neige';
$that['Few Snow Showers/Wind']='Quelques Averses de Neige/Vent';
$that['Light Snow/Wind']='Quelques flocons/vent';
$that['Wintry Mix']='Temps Hivernal';
$that['AM Wintry Mix']='Temps Hivernal le matin';
$that['Hvy Rain/Freezing Rain']='Forte Pluie/Pluie Verglaçante';
$that['AM Light Snow']='Neige légère le matin';
$that['Rain/Freezing Rain']='Pluie/Pluie verglassante';
$that['T-Storms/Wind']='Orages/Vent';
$that['Sprinkles']='Averses';
$that['AM Snow Showers']='Averses de Neige le matin';
$that['AM Clouds/PM Sun/Wind']='Matin Nuageux/Soleil A-Midi/Vent';
$that['AM Rain/Snow/Wind']='Pluie matinale/Neige/Vent';
$that['Rain to Snow/Wind']='Pluie puis Neige/Vent';
$that['Snow to Wintry Mix']='Neige puis Temps Hivernal';
$that['PM Snow Showers/Wind']='Averses de Neige A-Midi/Vent';
$that['Snow and Ice to Rain']='Neige et Verglas puis Pluie';
$that['Heavy Rain']='Forte Pluie';
$that['AM Rain/Ice']='Pluie matinale/Grêle';
$that['AM Snow Showers/Wind']='Averses de Neige le matin/Vent';
$that['AM Light Snow/Wind']='Neige légère le matin/Vent';
$that['PM Light Rain/Wind']='Pluie légère A-Midi/Vent';
$that['AM Light Wintry Mix']='Léger Temps Hivernal le matin';
$that['PM Light Snow/Wind']='Légère Neige A-Midi/Vent';
$that['Heavy Rain/Wind']='Forte Pluie/Vent';
$that['PM Snow Shower']='Averses de Neige A-Midi';
$that['Snow to Rain/Wind']='Neige puis Pluie/Vent';
$that['PM Light Rain/Ice']='Pluie légère A-Midi/Grêle';
$that['AM Snow']='Neige le matin';
$that['Snow to Ice']='Neige puis grêle';
$that['Wintry Mix/Wind']='Temps Hivernal/Vent';
$that['PM Light Snow']='Neige légère';
$that['AM Drizzle']='Bruine matinale';
$that['Strong Storms/Wind']='Gros orages/Vent';
$that['PM Drizzle']='Bruine';
$that['Drizzle']='Bruine';
$that['AM Light Rain/Wind']='Pluie légère le matin/Vent';
$that['AM Rain/Wind']='Pluie matinale/Vent';
$that['Wintry Mix to Snow']='Temps hivernal puis Neige';
$that['Snow Showers/Windy']='Averses de Neige/Vent';
$that['Light Rain Shower']='Légères averses';
$that['Light Rain with Thunder']='Pluie légère et Tonnerre';
$that['Light Drizzle']='Bruine légère';
$that['Mist']='Brume';
$that['Smoke']='Brouillard épais';
$that['Haze']='Ciel Voilé';
$that['Light Snow Shower']='Légères averses de Neige';
$that['Light Snow Shower/ Windy']='Légères averses de Neige/Vent';
$that['Clear']='Temps Clair';
$that['A Few Clouds']='Quelques Nuages';
$that['Fair']='Beau temps';
$that['Showers in the Vicinity']='Averses à proximité';
$that['New Moon']='Nouvelle Lune';
$that['Waxing Crescent']='Premier Croissant';
$that['First Quarter']='Premier Quartier';
$that['Waxing Gibbous']='Lune Gibbeuse Croissante';
$that['Full Moon']='Pleine Lune';
$that['Waning Gibbous']='Lune Gibbeuse décroissante';
*/





$label['meteo'] = $that;

?>
