<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/

//******************************************************************************
//PHOTO

//labels provenant de detail.php
$that['clic_expand']='Cliquer pour agrandir';
$that['unknown_format']='format inconnu';
$that['unknown_format_2']='Format inconnu : ';

//labels provenant de diaporama.php
$that['no_image']='Aucune image ici !';
$that['no_file']='Cette image est introuvable';
$that['folder_not_found']='Le dossier de photos n\'existe pas';

//labels provenant de download.php
$that['no_photo_dl']='Aucune photo à télécharger';

//labels provenant de index.php
$that['photo_album']='Album photos';
$that['no_album_year']='Pas d\'albums disponibles pour cette année';
$that['no_photo_album']='Pas de photos disponibles pour cet album';
$that['to_select']='Pour la sélection : ';
$that['move_to']='Déplacer vers :';
$that['change_right']='Changer les droits en :';
$that['album_previous_year']='Veuillez selectionner un album photo en choisissant une année anterieure';
$that['photo_book']='Albums Photo';
$that['photo_book_admin']='Administration de l\'album';
$that['visualisation']='Visualisation des photos de l\'album';
$that['error_iFrame']='Votre navigateur doit supporter les iFrames pour afficher cette page.';
$that['path']='Chemin d\'accès';
$that['default_photo']='Photo par défaut';
$that['acces_rights']='Droits d\'accès';

//labels provenant de xppub.php
$that['album_log_pass']='Veuillez entrer vos login et mot de passe etu (ceux avec lesquels vous vous connectez sur le site), pour pouvoir uploader vos photos sur l\'album';
$that['choose_directory']='Choose a directory to publish into';

$label['photos'] = $that;
$that=array();


?>
