<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//Annales

$that=array();
$that['list']='Fils RSS disponibles';
$that['admin']='Administratioin des fils RSS';
$that['no_rss']='Nous n\'avons aucun fil RSS à vous proposer.';
$that['feed_added']='Le fil RSS est à présent lisible dans votre module RSS.';
$that['feed_recorded']='Ce fil RSS est à présent disponible pour tous.';
$that['record_error']='Erreur lors de l\'enregistrement de ce fil RSS.';
 
$that['empty_field']='Tous les champs sont nécessaires à la création du fil RSS.';

$label['rss_feed'] = $that;
?>
