<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//Trombi

$that['presentation']='Veuillez s\'il vous plait, <strong>remplir scrupuleusement les informations suivantes</strong>.<br/>Le trombinoscope est un outil très pratique qui vous permet de retrouver très rapidement des informations sur les autres membres du site';
$that['champs_obligatoires']='Les champs suivis d\'une asterisque (*) sont obligatoires, les autres sont facultatifs pour avoir accès au trombinoscope, néanmoins ils sont fortement recommandés...';
$that['id_error']='Cette id ne vous appartient pas !';
$that['non_dispo_role']='Ce rôle est déja pris pour cette asso et ce semestre pour plus de détail contacter le webmaster';
//user/coordonnee.php
$that['invalid_sex']='Vous devez préciser votre sexe F : feminin, M : masculin';
$that['invalid_date']='Date invalide, le format doit etre JJ/MM/YY';
$that['invalid_gsm']='Vous devez entrer un numéro de Téléphone mobile valide';
$that['empty_gsm']='Vous devez entrer un numéro de Téléphone mobile';
$that['empty_email']='Vous devez entrer une adresse email';
$that['invalid_mail']='Vous devez entrer un e-mail perso valide';
$that['invalid_msn_mail']='Vous devez entrer un e-mail msn valide';
$that['invalid_webpage']='Vous devez entrer une adresse de page web valide';
$that['invalid_parental_phone']='Vous devez entrer un numéro de téléphone parental valide';
$that['invalid_phone']='Vous devez entrer un numéro de téléphone personnel valide';
$that['card_saved']='Vos informations ont bien été enregistrées';
$that['details_saved']='Coordonnées enregistrées';
$that['details_non_saved']='Coordonnées non enregistrées';
$that['jpg_only']='Seules les images dans le format jpeg sont acceptées.';
$that['del_error']='Erreur dans l\'effacement';
$that['no_picture']='Pas d\'image';
$that['add_picture']='Ajouter une image';
$that['non_change_info']='Vos passions ne sont plus modifiables';
$that['remaining_letter']='Nombre de caractères restants';
$that['non_exist']='Vous n\'existez pas pas dans la base du trombi';


$that['nc']='Non communiqué';
$that['general_info']='Informations générales';
$that['infos_perso']='Informations perso';
$that['infos_perso']='Informations personnelles';
$that['infos_suppl']='Infos Supplémentaires';
$that['other_info']='Infos Supplémentaires';
$that['contact']='Contacts';
$that['sexe']='sexe';
$that['sexe_m']='M';
$that['sexe_f']='F';
$that['date_naiss']='Date de naissance (jj/mm/aaaa)';
$that['tel_portable']='Tél. Portable';
$that['mobile_phone']='Tél. portable';
$that['mail_perso']='Email Perso';
$that['mail_msn']='Email MSN';
$that['mail_autre']='Autre Mes. Inst. (ICQ, trillian, aim... Ã Â  preciser)';
$that['icq']='ICQ';
$that['web_site']='Site Web Perso';
$that['web_page']='Site Web';
$that['web_page_pro']='Site Web pro';
$that['adresse_princ']='Adresse principale';
$that['adresse_sec']='Adresse secondaire';
$that['parent_adress']='Adresse chez les parents';
$that['description_perso']='Passions/Hobbies';
$that['rue']='Rue';
$that['street']='Rue';
$that['code_postal']='Code postal';
$that['postal_code']='Code postal';
$that['ville']='Ville';
$that['town']='Ville';
$that['pays']='Pays';
$that['country']='Pays';
$that['telephone']='Téléphone';
$that['phone']='Téléphone';
$that['home_phone']='Téléphone fixe';
$that['present_addr']='Adresse actuelle (à Troyes, en stage ou à  l\'étranger)';
$that['ext_period']='Semestre hors cursus';
$that['type']='Type';
$that['company']='Entreprise';
$that['beginning']='Début';
$that['end']='Fin';
$that['period']='Semestre';
$that['exchange_period']='Semestre à  l\'étranger';
$that['club_and_asso']='Club et Asso';
$that['asso']='Asso';
$that['role']='Rôle';



$that['surnom']='Pseudo(s)';
$that['nickname']='Pseudo(s)';
$that['jadis']='Jadis';
$that['before']='Jadis';
$that['hobbies']='Hobbies';
$that['nb_carac_restant']='Nombre de caractères restants';
$that['remarque_verrou_trombi']='Remarque : Tant que vous n\'aurez pas renseignés correctement TOUS les champs obligatoires, vous ne pourrez pas vous servir du trombinoscope';

$that['remplir_fiche_pour_acceder_trombi']='Tant que vous n\'aurez pas saisi votre fiche, vous ne pourrez utiliser le trombi.';

//trombi/index.php
$that['name_nick_uv']='nom, prénom, ou tél';
$that['my_major']='Ma branche';
$that['my_uv']='Mes uvs';
$that['advanced_seek']='Recherche avancée';
$that['simple_seek']='Simple';
$that['see_all']='Voir tout le monde';
$that['search_result']='Résultats de la recherche';
$that['s_inval_name']='Nom invalide';
$that['s_inval_firstname']='Prénom invalide';
$that['s_inval_webpage']='Page web invalide';
$that['s_inval_nick']='Pseudo invalide';
$that['s_inval_uv']='UV invalide';
$that['s_inval_dep']='Département invalide';
$that['s_inval_town']='Ville invalide';
$that['s_inval_country']='Pays invalide';
$that['s_inval_phone']='Téléphone invalide';
$that['s_inval_msn']='Adresse MSN invalide';
$that['s_inval_mail']='E-mail personnel invalide';
$that['indif']='Indif.';
$that['all_student']='Tous les Etu.';
$that['exchange_student']='Etu. international';
$that['docto']='Thêsard';
$that['master']='Master';
$that['dess']='DESS';
$that['admin']='Administration';
$that['teacher']='Prof/chercheur';
$that['free_student']='Auditeur libre';
$that['intern']='Stagiaire';
$that['status']='Statut';
$that['major_period']='Branche | n° sem.';
$that['hidde_fields']='Masquer ces champs';
$that['other_fields']='Autres champs';
$that['trombi_info']='Informations du trombi';
$that['departement']='Département';
$that['department']='Département';
$that['phone_all']='Téléphone (gsm/fixe)';
$that['exact_term']='Termes exacts';
$that['change_card']='Modifier ma fiche';
$that['today_birth']='Anniversaires du jour';
$that['birthday_alert']='Nofifications d\'anniversaire';
$that['nb_users_fill']='[1] utilisateur(s) sur [2] ont rempli leur fiche';
$that['pref']='Préférences';
$that['card_per_page']='Fiches par page';
$that['show_pictures']='Afficher les photos';
$that['select_one_crit']='Sélectionnez au moins un critère';
$that['results']='réponse(s)';
$that['sort_by']='Trier par';
$that['page']='page';
$that['Page']='Page';
$that['no_result']='Aucun individu ne correspond à votre recherche';
$that['download_vcard']='Télécharger la Vcard de cette personne, il s agit d un format de carte virtuelle contenant toutes les informations sur la personne !';

// Valeur utilisé dans trombi modifiable
$that['data_error']='Votre fiche n\'a pas pu être enregistrée.';
$that['last_added']='Derniers inscrits';


//Extérieur au trombi
$that['click_to_change_status']='Cliquez pour changer votre signal social';
$that['trombi_card']='fiche trombi';

$label['trombi'] = $that;
$that=array();

?>
