<?php
/**
*   Copyright : (C) 2007 Wope
*   License : GNU GPL
*   Contact : http://www.wope-project.org
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston,
*   MA  02111-1307  USA
*
**/


//******************************************************************************
//UVs

//labels provenant de new.php
$that['uv_choice']='Choix UV';
$that['see_uv']='Voir mes uvs';
$that['classify_uv']='Classement des uvs';
$that['caption']='Légende';
$that['fr_contents']=' Contenu en Français';
$that['br_contents']=' Contenu en Anglais';
$that['announce_prob']=' Signaler un problème';
$that['word_doc']=' Document Word';
$that['pdf_doc']=' Document Pdf';
$that['scan_doc']=' Document scanné';
$that['filter_uv_type']='Filtrer les types d\'uv :';
$that['all_type']='Tous les types :';
$that['uv']='UV';
$that['note_average']='Note myenne';
$that['nb_opinion']='Nb avis';

//labels provenant de index.php

$that['%_success']='Pourcentage de réussite :';
$that['await_result']='Attente des résultats';
$that['can_write_on']='Vous ne pourrez rédiger votre avis sur cette uv qu\'à  la date du 1er [1]';
$that['choice_uv']='Choix UV';
$that['choice_uv_2']='"Choisissez une UV"';
$that['consult_student_uv']='Consulter la liste des étudiants qui font [1] ce semestre';
$that['fianl_exam']='finaux';
$that['interrogation']='interros';
$that['medium_exam']='medians';
$that['mes_uvs']='Mes uvs';
$that['modify_eva_uv']='Modifier l\'évaluation de [1] pour [2] :';
$that['name_uv']='Le nom de l\'uv [1] n\'est pas correct';
$that['no_eval']='Aucune évaluation pour l\'uv [1] n\'a été faite pour le moment.';
$that['nb_opinion_1']='Déjà [1] avis ont été rédigés pour cette uv.';
$that['nb_opinion_2']='Déjà [1] avis a été rédigé pour cette uv.';
$that['nb_opinion_3']='Aucun avis n\'a été rédigé pour cette uv.';
$that['no_heading_project_available']='La rubrique \"Projets Rapports TP\" n\'est pas encore disponible';
$that['no_heading_available']='La rubrique \"Cours et autres\" n\'est pas encore disponible';
$that['note_uv']='Note attribuée à [1] : [2]';
$that['opinion_seen']='Confirmez votre opinion :';
$that['partial_exam']='partiels';
$that['previsualize']='Prévisualiser';
$that['propose_exam_uv']='Proposer une nouvelle annale pour [1]';
$that['propose_www_uv']='Proposer une nouvelle adresse Web pour [1]';
$that['question_mult_choice']='QCM';
$that['save_opinion']='Votre avis a bien été enregistrée !';
$that['send_mail_uv']='Envoyer un mail à tous les étudiants qui font [1] ce semestre';
$that['uv_opinion']='Notez l\'uv :';
$that['warning_uv_1']='Pas de langage SMS, pas d\'insultes, attention aux fautes d\'orthographe. Restez correct.';
$that['warning_uv_2']='Après avoir validé définitivement votre avis, <strong>vous ne pourrez plus le modifier !</strong>';
$that['warning_uv_3']='Les profs peuvent consulter les avis mais sans savoir qui les a écrit.';
$that['write_opinion']='Rédigez un avis sur l\'uv [1] :';

//labels provenant de mes_uvs.php
$that['opinion']='Avis';
$that['note_obtained']='Note obtenue';
$that['notation']='Notation';
$that['no_opinion_yet']='Vous n\'avez pas encore rédigé d\'avis';
$that['await_1']='Attendez le 1er [1] pour pouvoir le rédiger';

$label['uv'] = $that;
$label['uvs'] = $that;
$that=array();



