#!/bin/bash

for i in `find . -type f -name "*.php"`
do
		name=`basename $i`
		
		cp $i /tmp/
		
		cat /tmp/$name | iconv -f latin1 -t latin1 > $i

		cp $i /tmp/
		
		cat /tmp/$name | iconv -f latin1 -t utf-8 > $i

done	

for i in `find . -type f -name "*.inc"`
do
		name=`basename $i`

		cp $i /tmp/
		
		cat /tmp/$name | iconv -f latin1 -t latin1 > $i
		
		cp $i /tmp/
		
		cat /tmp/$name | iconv -f latin1 -t utf-8 > $i
done	
